export default {
  LOAD_PODCAST_EPISODE: 'LOAD_PODCAST_EPISODE',
  CLEAR_PODCAST_EPISODE: 'CLEAR_PODCAST_EPISODE',
  ADD_PODCASTS: 'ADD_PODCASTS',
  ADD_EPISODE_TO_QUEUE: 'ADD_EPISODE_TO_QUEUE',
  REMOVE_EPISODE_FROM_QUEUE: 'REMOVE_EPISODE_FROM_QUEUE'
};